'use client';

import { useI18n } from '../../lib/i18n';

const privacyEn = `
<h1>Privacy Policy</h1>
<p>Last updated: August 21, 2025</p>
<p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
<p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.freeprivacypolicy.com/free-privacy-policy-generator/" target="_blank" rel="noreferrer">Free Privacy Policy Generator</a>.</p>
<h2>Interpretation and Definitions</h2>
<h3>Interpretation</h3>
<p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
<h3>Definitions</h3>
<p>For the purposes of this Privacy Policy:</p>
<ul>
<li><p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p></li>
<li><p><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p></li>
<li><p><strong>Application</strong> refers to Spielplan, the software program provided by the Company.</p></li>
<li><p><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Spielplan.</p></li>
<li><p><strong>Country</strong> refers to: Berlin,  Germany</p></li>
<li><p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p></li>
<li><p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p></li>
<li><p><strong>Service</strong> refers to the Application.</p></li>
<li><p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p></li>
<li><p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p></li>
<li><p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p></li>
</ul>
<h2>Collecting and Using Your Personal Data</h2>
<h3>Types of Data Collected</h3>
<h4>Personal Data</h4>
<p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
<ul>
<li><p>First name and last name</p></li>
<li><p>Usage Data</p></li>
</ul>
<h4>Usage Data</h4>
<p>Usage Data is collected automatically when using the Service.</p>
<p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
<p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
<p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
<h3>Use of Your Personal Data</h3>
<p>The Company may use Personal Data for the following purposes:</p>
<ul>
<li><p><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</p></li>
<li><p><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</p></li>
<li><p><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</p></li>
<li><p><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</p></li>
<li><p><strong>To provide You</strong> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</p></li>
<li><p><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</p></li>
<li><p><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</p></li>
<li><p><strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</p></li>
</ul>
<p>We may share Your personal information in the following situations:</p>
<ul>
<li><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service,  to contact You.</li>
<li><strong>For business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
<li><strong>With Affiliates:</strong> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
<li><strong>With business partners:</strong> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
<li><strong>With other users:</strong> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
<li><strong>With Your consent</strong>: We may disclose Your personal information for any other purpose with Your consent.</li>
</ul>
<h3>Retention of Your Personal Data</h3>
<p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
<p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>
<h3>Transfer of Your Personal Data</h3>
<p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
<p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
<p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
<h3>Delete Your Personal Data</h3>
<p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
<p>Our Service may give You the ability to delete certain information about You from within the Service.</p>
<p>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</p>
<p>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>
<h3>Disclosure of Your Personal Data</h3>
<h4>Business Transactions</h4>
<p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
<h4>Law enforcement</h4>
<p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
<h4>Other legal requirements</h4>
<p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
<ul>
<li>Comply with a legal obligation</li>
<li>Protect and defend the rights or property of the Company</li>
<li>Prevent or investigate possible wrongdoing in connection with the Service</li>
<li>Protect the personal safety of Users of the Service or the public</li>
<li>Protect against legal liability</li>
</ul>
<h3>Security of Your Personal Data</h3>
<p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
<h2>Children's Privacy</h2>
<p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
<p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
<h2>Links to Other Websites</h2>
<p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
<p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
<h2>Changes to this Privacy Policy</h2>
<p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
<p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
<p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
<h2>Contact Us</h2>
<p>If you have any questions about this Privacy Policy, You can contact us:</p>
<ul>
<li>By email: hoppers_hedges.9b@icloud.com</li>
</ul>
`;

const privacyDe = `
<h1>Datenschutzerklärung</h1>
<p>Letzte Aktualisierung: 21. August 2025</p>
<p>Diese Datenschutzerklärung beschreibt unsere Richtlinien und Verfahren zur Erhebung, Nutzung und Offenlegung Ihrer Informationen, wenn Sie den Dienst nutzen, und informiert Sie über Ihre Datenschutzrechte und wie das Gesetz Sie schützt.</p>
<p>Wir verwenden Ihre personenbezogenen Daten, um den Dienst bereitzustellen und zu verbessern. Durch die Nutzung des Dienstes stimmen Sie der Erhebung und Nutzung von Informationen gemäß dieser Datenschutzerklärung zu. Diese Datenschutzerklärung wurde mit Hilfe des <a href="https://www.freeprivacypolicy.com/free-privacy-policy-generator/" target="_blank" rel="noreferrer">Free Privacy Policy Generators</a> erstellt.</p>
<h2>Auslegung und Definitionen</h2>
<h3>Auslegung</h3>
<p>Wörter, deren Anfangsbuchstabe großgeschrieben ist, haben die nachfolgend definierten Bedeutungen. Die folgenden Definitionen haben die gleiche Bedeutung, unabhängig davon, ob sie im Singular oder Plural erscheinen.</p>
<h3>Definitionen</h3>
<p>Für die Zwecke dieser Datenschutzerklärung:</p>
<ul>
<li><p><strong>Konto</strong> bezeichnet ein einzigartiges Konto, das für Sie erstellt wurde, um auf unseren Dienst oder Teile unseres Dienstes zuzugreifen.</p></li>
<li><p><strong>Verbundenes Unternehmen</strong> bezeichnet eine Einheit, die eine Partei kontrolliert, von ihr kontrolliert wird oder unter gemeinsamer Kontrolle mit ihr steht, wobei "Kontrolle" den Besitz von 50 % oder mehr der Anteile, Kapitalbeteiligungen oder anderen stimmberechtigten Wertpapiere zur Wahl von Direktoren oder anderer geschäftsführender Organe bedeutet.</p></li>
<li><p><strong>Anwendung</strong> bezeichnet Spielplan, das vom Unternehmen bereitgestellte Softwareprogramm.</p></li>
<li><p><strong>Unternehmen</strong> (in dieser Vereinbarung als „das Unternehmen“, „wir“, „uns“ oder „unser“ bezeichnet) bezeichnet Spielplan.</p></li>
<li><p><strong>Land</strong> bezieht sich auf: Berlin, Deutschland</p></li>
<li><p><strong>Gerät</strong> bezeichnet jedes Gerät, das auf den Dienst zugreifen kann, wie ein Computer, ein Mobiltelefon oder ein Tablet.</p></li>
<li><p><strong>Personenbezogene Daten</strong> sind alle Informationen, die sich auf eine identifizierte oder identifizierbare natürliche Person beziehen.</p></li>
<li><p><strong>Dienst</strong> bezeichnet die Anwendung.</p></li>
<li><p><strong>Dienstanbieter</strong> bezeichnet jede natürliche oder juristische Person, die die Daten im Auftrag des Unternehmens verarbeitet. Hierzu zählen Drittunternehmen oder Einzelpersonen, die vom Unternehmen beauftragt sind, den Dienst zu erleichtern, den Dienst im Namen des Unternehmens bereitzustellen, dienstbezogene Leistungen zu erbringen oder dem Unternehmen bei der Analyse zu helfen, wie der Dienst genutzt wird.</p></li>
<li><p><strong>Nutzungsdaten</strong> sind Daten, die automatisch erfasst werden, entweder durch die Nutzung des Dienstes oder aus der Dienstinfrastruktur selbst (z. B. die Dauer eines Seitenbesuchs).</p></li>
<li><p><strong>Sie</strong> bezeichnet die Person, die auf den Dienst zugreift oder ihn nutzt, oder das Unternehmen bzw. die andere juristische Person, in deren Namen eine solche Person auf den Dienst zugreift oder ihn nutzt, sofern zutreffend.</p></li>
</ul>
<h2>Erfassung und Verwendung Ihrer personenbezogenen Daten</h2>
<h3>Arten der erfassten Daten</h3>
<h4>Personenbezogene Daten</h4>
<p>Während der Nutzung unseres Dienstes können wir Sie bitten, uns bestimmte personenbezogene Daten zur Verfügung zu stellen, die zur Kontaktaufnahme oder Identifizierung Ihrer Person verwendet werden können. Personenbezogene Daten können unter anderem Folgendes umfassen:</p>
<ul>
<li><p>Vor- und Nachname</p></li>
<li><p>Nutzungsdaten</p></li>
</ul>
<h4>Nutzungsdaten</h4>
<p>Nutzungsdaten werden bei der Nutzung des Dienstes automatisch erfasst.</p>
<p>Zu den Nutzungsdaten können Informationen wie die IP-Adresse Ihres Geräts, Browsertyp, Browserversion, die Seiten unseres Dienstes, die Sie besuchen, Datum und Uhrzeit Ihres Besuchs, die auf diesen Seiten verbrachte Zeit, eindeutige Gerätekennungen und andere Diagnosedaten gehören.</p>
<p>Wenn Sie über ein mobiles Gerät auf den Dienst zugreifen, können wir bestimmte Informationen automatisch erfassen, einschließlich, aber nicht beschränkt auf die Art des von Ihnen verwendeten mobilen Geräts, die eindeutige Geräte-ID, die IP-Adresse Ihres mobilen Geräts, Ihr mobiles Betriebssystem, den Typ des von Ihnen verwendeten mobilen Internetbrowsers, eindeutige Gerätekennungen und andere Diagnosedaten.</p>
<p>Wir können auch Informationen erfassen, die Ihr Browser sendet, wenn Sie unseren Dienst besuchen oder wenn Sie über ein mobiles Gerät auf den Dienst zugreifen.</p>
<h3>Verwendung Ihrer personenbezogenen Daten</h3>
<p>Das Unternehmen kann personenbezogene Daten für die folgenden Zwecke verwenden:</p>
<ul>
<li><p><strong>Zur Bereitstellung und Aufrechterhaltung unseres Dienstes</strong>, einschließlich der Überwachung der Nutzung unseres Dienstes.</p></li>
<li><p><strong>Zur Verwaltung Ihres Kontos:</strong> zur Verwaltung Ihrer Registrierung als Nutzer des Dienstes. Die von Ihnen bereitgestellten personenbezogenen Daten können Ihnen Zugang zu verschiedenen Funktionen des Dienstes verschaffen, die Ihnen als registriertem Nutzer zur Verfügung stehen.</p></li>
<li><p><strong>Zur Erfüllung eines Vertrags:</strong> die Entwicklung, Erfüllung und Durchführung des Kaufvertrags über die von Ihnen erworbenen Produkte, Artikel oder Dienstleistungen oder eines anderen Vertrags mit uns über den Dienst.</p></li>
<li><p><strong>Zur Kontaktaufnahme mit Ihnen:</strong> Zur Kontaktaufnahme per E-Mail, Telefonanrufen, SMS oder anderen vergleichbaren Formen der elektronischen Kommunikation, wie Push-Benachrichtigungen einer mobilen Anwendung, bezüglich Updates oder informativer Mitteilungen im Zusammenhang mit den Funktionen, Produkten oder vertraglich vereinbarten Dienstleistungen, einschließlich Sicherheitsupdates, wenn dies für deren Umsetzung notwendig oder angemessen ist.</p></li>
<li><p><strong>Zur Bereitstellung</strong> von Neuigkeiten, Sonderangeboten und allgemeinen Informationen über andere Waren, Dienstleistungen und Veranstaltungen, die wir anbieten und die denen ähnlich sind, die Sie bereits gekauft haben oder nach denen Sie sich erkundigt haben, sofern Sie nicht angegeben haben, dass Sie solche Informationen nicht erhalten möchten.</p></li>
<li><p><strong>Zur Verwaltung Ihrer Anfragen:</strong> Zur Bearbeitung und Verwaltung Ihrer Anfragen an uns.</p></li>
<li><p><strong>Für Unternehmensübertragungen:</strong> Wir können Ihre Informationen verwenden, um eine Fusion, Veräußerung, Umstrukturierung, Reorganisation, Auflösung oder einen anderen Verkauf oder eine Übertragung einiger oder aller unserer Vermögenswerte zu bewerten oder durchzuführen, sei es als fortgeführtes Unternehmen oder im Rahmen eines Insolvenz-, Liquidations- oder ähnlichen Verfahrens, bei dem personenbezogene Daten, die wir über Nutzer unseres Dienstes gespeichert haben, zu den übertragenen Vermögenswerten gehören.</p></li>
<li><p><strong>Für andere Zwecke</strong>: Wir können Ihre Informationen für andere Zwecke verwenden, wie z. B. Datenanalyse, Identifizierung von Nutzungstrends, Bestimmung der Wirksamkeit unserer Werbekampagnen sowie zur Bewertung und Verbesserung unseres Dienstes, unserer Produkte, Dienstleistungen, unseres Marketings und Ihrer Erfahrung.</p></li>
</ul>
<p>Wir können Ihre personenbezogenen Informationen in den folgenden Situationen weitergeben:</p>
<ul>
<li><strong>Mit Dienstanbietern:</strong> Wir können Ihre personenbezogenen Informationen mit Dienstanbietern teilen, um die Nutzung unseres Dienstes zu überwachen und zu analysieren oder um Sie zu kontaktieren.</li>
<li><strong>Bei Unternehmensübertragungen:</strong> Wir können Ihre personenbezogenen Informationen im Zusammenhang mit oder während Verhandlungen über eine Fusion, einen Verkauf von Unternehmensvermögen, eine Finanzierung oder eine Übernahme unseres gesamten oder eines Teils unseres Unternehmens an ein anderes Unternehmen weitergeben oder übertragen.</li>
<li><strong>Mit verbundenen Unternehmen:</strong> Wir können Ihre Informationen mit unseren verbundenen Unternehmen teilen, in diesem Fall werden wir diese veranlassen, diese Datenschutzerklärung zu beachten. Zu den verbundenen Unternehmen gehören unsere Muttergesellschaft und alle anderen Tochtergesellschaften, Joint-Venture-Partner oder andere Unternehmen, die wir kontrollieren oder die mit uns unter gemeinsamer Kontrolle stehen.</li>
<li><strong>Mit Geschäftspartnern:</strong> Wir können Ihre Informationen mit unseren Geschäftspartnern teilen, um Ihnen bestimmte Produkte, Dienstleistungen oder Werbeaktionen anzubieten.</li>
<li><strong>Mit anderen Nutzern:</strong> Wenn Sie in öffentlichen Bereichen mit anderen Nutzern persönliche Informationen teilen oder anderweitig interagieren, können diese Informationen von allen Nutzern eingesehen und außerhalb öffentlich verbreitet werden.</li>
<li><strong>Mit Ihrer Zustimmung</strong>: Wir können Ihre persönlichen Informationen für jeden anderen Zweck mit Ihrer Zustimmung offenlegen.</li>
</ul>
<h3>Aufbewahrung Ihrer personenbezogenen Daten</h3>
<p>Das Unternehmen bewahrt Ihre personenbezogenen Daten nur so lange auf, wie es für die in dieser Datenschutzerklärung dargelegten Zwecke erforderlich ist. Wir bewahren Ihre personenbezogenen Daten in dem Umfang auf und verwenden sie, wie es erforderlich ist, um unseren gesetzlichen Verpflichtungen nachzukommen (zum Beispiel, wenn wir Ihre Daten aufbewahren müssen, um geltendem Recht zu entsprechen), Streitigkeiten zu lösen und unsere rechtlichen Vereinbarungen und Richtlinien durchzusetzen.</p>
<p>Das Unternehmen bewahrt auch Nutzungsdaten für interne Analysezwecke auf. Nutzungsdaten werden in der Regel für einen kürzeren Zeitraum aufbewahrt, es sei denn, diese Daten werden verwendet, um die Sicherheit zu stärken oder die Funktionalität unseres Dienstes zu verbessern, oder wir sind rechtlich verpflichtet, diese Daten über längere Zeiträume aufzubewahren.</p>
<h3>Übermittlung Ihrer personenbezogenen Daten</h3>
<p>Ihre Informationen, einschließlich personenbezogener Daten, werden in den Betriebsbüros des Unternehmens und an allen anderen Orten verarbeitet, an denen sich die an der Verarbeitung beteiligten Parteien befinden. Das bedeutet, dass diese Informationen auf Computer übertragen und dort gespeichert werden können, die sich außerhalb Ihres Bundeslandes, Ihrer Provinz, Ihres Landes oder einer anderen staatlichen Zuständigkeit befinden, in der die Datenschutzgesetze von denen Ihrer Zuständigkeit abweichen können.</p>
<p>Ihre Zustimmung zu dieser Datenschutzerklärung, gefolgt von der Übermittlung solcher Informationen, stellt Ihre Zustimmung zu dieser Übertragung dar.</p>
<p>Das Unternehmen wird alle angemessenen Schritte unternehmen, um sicherzustellen, dass Ihre Daten sicher und in Übereinstimmung mit dieser Datenschutzerklärung behandelt werden und keine Übermittlung Ihrer personenbezogenen Daten an eine Organisation oder ein Land erfolgt, sofern nicht angemessene Kontrollen vorhanden sind, einschließlich der Sicherheit Ihrer Daten und anderer persönlicher Informationen.</p>
<h3>Löschen Ihrer personenbezogenen Daten</h3>
<p>Sie haben das Recht, die personenbezogenen Daten, die wir über Sie erhoben haben, zu löschen oder zu verlangen, dass wir Sie beim Löschen unterstützen.</p>
<p>Unser Dienst kann Ihnen die Möglichkeit geben, bestimmte Informationen über Sie innerhalb des Dienstes zu löschen.</p>
<p>Sie können Ihre Informationen jederzeit aktualisieren, ändern oder löschen, indem Sie sich bei Ihrem Konto anmelden, sofern Sie eines haben, und den Bereich mit den Kontoeinstellungen besuchen, der es Ihnen ermöglicht, Ihre persönlichen Informationen zu verwalten. Sie können uns auch kontaktieren, um Zugriff auf persönliche Informationen anzufordern, die Sie uns bereitgestellt haben, diese zu korrigieren oder zu löschen.</p>
<p>Bitte beachten Sie jedoch, dass wir bestimmte Informationen aufbewahren müssen, wenn wir eine rechtliche Verpflichtung oder eine rechtmäßige Grundlage dafür haben.</p>
<h3>Offenlegung Ihrer personenbezogenen Daten</h3>
<h4>Unternehmensübertragungen</h4>
<p>Wenn das Unternehmen an einer Fusion, Übernahme oder einem Verkauf von Vermögenswerten beteiligt ist, können Ihre personenbezogenen Daten übertragen werden. Wir werden Sie benachrichtigen, bevor Ihre personenbezogenen Daten übertragen werden und einer anderen Datenschutzerklärung unterliegen.</p>
<h4>Strafverfolgung</h4>
<p>Unter bestimmten Umständen kann das Unternehmen verpflichtet sein, Ihre personenbezogenen Daten offenzulegen, wenn dies gesetzlich vorgeschrieben ist oder als Reaktion auf gültige Anfragen durch öffentliche Behörden (z. B. ein Gericht oder eine Regierungsbehörde).</p>
<h4>Andere rechtliche Anforderungen</h4>
<p>Das Unternehmen kann Ihre personenbezogenen Daten in dem guten Glauben offenlegen, dass eine solche Maßnahme notwendig ist, um:</p>
<ul>
<li>Einer gesetzlichen Verpflichtung nachzukommen</li>
<li>Die Rechte oder das Eigentum des Unternehmens zu schützen und zu verteidigen</li>
<li> Mögliche Vergehen im Zusammenhang mit dem Dienst zu verhindern oder zu untersuchen</li>
<li>Die persönliche Sicherheit der Nutzer des Dienstes oder der Öffentlichkeit zu schützen</li>
<li>Gegen rechtliche Haftung zu schützen</li>
</ul>
<h3>Sicherheit Ihrer personenbezogenen Daten</h3>
<p>Die Sicherheit Ihrer personenbezogenen Daten ist uns wichtig, aber denken Sie daran, dass keine Methode der Übertragung über das Internet oder Methode der elektronischen Speicherung zu 100 % sicher ist. Obwohl wir uns bemühen, kommerziell akzeptable Mittel zum Schutz Ihrer personenbezogenen Daten zu verwenden, können wir deren absolute Sicherheit nicht garantieren.</p>
<h2>Datenschutz von Kindern</h2>
<p>Unser Dienst richtet sich nicht an Personen unter 13 Jahren. Wir erfassen nicht wissentlich personenbezogene Daten von Personen unter 13 Jahren. Wenn Sie ein Elternteil oder Vormund sind und Ihnen bekannt ist, dass Ihr Kind uns personenbezogene Daten zur Verfügung gestellt hat, kontaktieren Sie uns bitte. Wenn wir erfahren, dass wir personenbezogene Daten von Personen unter 13 Jahren ohne Verifizierung der elterlichen Zustimmung erfasst haben, ergreifen wir Maßnahmen, um diese Informationen von unseren Servern zu entfernen.</p>
<p>Wenn wir uns auf die Einwilligung als Rechtsgrundlage für die Verarbeitung Ihrer Informationen stützen müssen und Ihr Land die Einwilligung eines Elternteils verlangt, können wir die Einwilligung eines Elternteils einholen, bevor wir diese Informationen erfassen und verwenden.</p>
<h2>Links zu anderen Websites</h2>
<p>Unser Dienst kann Links zu anderen Websites enthalten, die nicht von uns betrieben werden. Wenn Sie auf einen Link eines Drittanbieters klicken, werden Sie zu der Website dieses Drittanbieters weitergeleitet. Wir empfehlen Ihnen dringend, die Datenschutzerklärung jeder Website zu lesen, die Sie besuchen.</p>
<p>Wir haben keine Kontrolle über die Inhalte, Datenschutzrichtlinien oder Praktiken von Websites oder Diensten Dritter und übernehmen keine Verantwortung dafür.</p>
<h2>Änderungen an dieser Datenschutzerklärung</h2>
<p>Wir können unsere Datenschutzerklärung von Zeit zu Zeit aktualisieren. Wir werden Sie über alle Änderungen informieren, indem wir die neue Datenschutzerklärung auf dieser Seite veröffentlichen.</p>
<p>Wir werden Sie per E-Mail und/oder durch einen deutlich sichtbaren Hinweis auf unserem Dienst informieren, bevor die Änderung wirksam wird, und das Datum der „Letzten Aktualisierung“ oben in dieser Datenschutzerklärung aktualisieren.</p>
<p>Es wird empfohlen, diese Datenschutzerklärung regelmäßig auf Änderungen zu überprüfen. Änderungen an dieser Datenschutzerklärung treten in Kraft, wenn sie auf dieser Seite veröffentlicht werden.</p>
<h2>Kontakt</h2>
<p>Wenn Sie Fragen zu dieser Datenschutzerklärung haben, können Sie uns kontaktieren:</p>
<ul>
<li>Per E-Mail: hoppers_hedges.9b@icloud.com</li>
</ul>
`;

export default function PrivacyPage() {
  const { t, locale } = useI18n() as any;
  const html = locale === 'de' ? privacyDe : privacyEn;
  return (
    <main className="container grid">
      <div className="flex" style={{gap:8, alignItems:'center'}}>
        <a href="/" className="btn">{t('nav.back')}</a>
        <h1 style={{margin:'0 0 0 .5rem'}}>{t('privacy.title')}</h1>
      </div>
      <section className="card">
        <div dangerouslySetInnerHTML={{ __html: html }} />
      </section>
    </main>
  );
}
